"""Stub file for custom_components/reflex_perspective/viewer.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
import reflex as rx
from reflex.vars import Var

PERSPECTIVE_VERSION = "5.5.1"
"npm version of the ``@perspective-dev/*`` packages bundled by this component.\n\nKeep it aligned with the ``perspective-python`` version when using server\nmodes: the WebSocket protocol is versioned together.\n"
PluginName = Literal[
    "Datagrid",
    "X Bar",
    "Y Bar",
    "Y Line",
    "Y Scatter",
    "Y Area",
    "X/Y Scatter",
    "X/Y Line",
    "Density",
    "Treemap",
    "Sunburst",
    "Heatmap",
    "Candlestick",
    "OHLC",
    "Map Scatter",
    "Map Line",
    "Map Density",
]
PLUGINS: list[str]
"Plugins registered by ``@perspective-dev/viewer-datagrid`` and ``-charts``."
THEMES: list[str]
"Theme names bundled in ``@perspective-dev/viewer/dist/css/themes.css``."
AGGREGATES: list[str]
"Common aggregate names accepted in ``aggregates={column: aggregate}``."
EXPORT_METHODS: list[str]
EditMode = Literal[
    "READ_ONLY",
    "EDIT",
    "SELECT_COLUMN",
    "SELECT_ROW",
    "SELECT_REGION",
    "SELECT_ROW_TREE",
]
_BRIDGE = rx.asset("perspective_viewer.jsx", shared=True)

class PerspectiveViewer(rx.Component):
    @classmethod
    def create(
        cls,
        *children,
        data: Var[dict[str, list[Any]] | list[dict[str, Any]] | str]
        | dict[str, list[Any]]
        | list[dict[str, Any]]
        | str
        | None = None,
        schema: Var[dict[str, str]] | dict[str, str] | None = None,
        index: Var[str] | str | None = None,
        limit: Var[int] | int | None = None,
        table_name: Var[str] | str | None = None,
        url: Var[str] | str | None = None,
        url_format: Literal["arrow", "csv", "json", "ndjson"]
        | Var[Literal["arrow", "csv", "json", "ndjson"]]
        | None = None,
        server_url: Var[str] | str | None = None,
        server_table: Var[str] | str | None = None,
        server_mode: Literal["replicated", "server"]
        | Var[Literal["replicated", "server"]]
        | None = None,
        update_rows: Var[dict[str, list[Any]] | list[dict[str, Any]]]
        | dict[str, list[Any]]
        | list[dict[str, Any]]
        | None = None,
        remove_keys: Var[list[Any]] | list[Any] | None = None,
        config: Var[dict[str, Any]] | dict[str, Any] | None = None,
        workspace: Var[dict[str, Any]] | dict[str, Any] | None = None,
        plugin: Var[str] | str | None = None,
        columns: Var[list[str | None]] | list[str | None] | None = None,
        group_by: Var[list[str]] | list[str] | None = None,
        split_by: Var[list[str]] | list[str] | None = None,
        filter: Var[list[list[Any]]] | list[list[Any]] | None = None,
        filter_op: Literal["and", "or"] | Var[Literal["and", "or"]] | None = None,
        sort: Var[list[list[str]]] | list[list[str]] | None = None,
        expressions: Var[dict[str, str]] | dict[str, str] | None = None,
        aggregates: Var[dict[str, Any]] | dict[str, Any] | None = None,
        group_by_depth: Var[int] | int | None = None,
        group_rollup_mode: Literal["flat", "rollup", "total"]
        | Var[Literal["flat", "rollup", "total"]]
        | None = None,
        split_rollup_mode: Literal["flat", "rollup"]
        | Var[Literal["flat", "rollup"]]
        | None = None,
        plugin_config: Var[dict[str, Any]] | dict[str, Any] | None = None,
        columns_config: Var[dict[str, dict[str, Any]]]
        | dict[str, dict[str, Any]]
        | None = None,
        theme: Var[str] | str | None = None,
        title: Var[str] | str | None = None,
        settings: Var[bool] | bool | None = None,
        edit_mode: Literal[
            "EDIT",
            "READ_ONLY",
            "SELECT_COLUMN",
            "SELECT_REGION",
            "SELECT_ROW",
            "SELECT_ROW_TREE",
        ]
        | Var[
            Literal[
                "EDIT",
                "READ_ONLY",
                "SELECT_COLUMN",
                "SELECT_REGION",
                "SELECT_ROW",
                "SELECT_ROW_TREE",
            ]
        ]
        | None = None,
        auto_size: Var[bool] | bool | None = None,
        auto_pause: Var[bool] | bool | None = None,
        throttle: Var[int] | int | None = None,
        plugin_limits: Var[dict[str, dict[str, int]]]
        | dict[str, dict[str, int]]
        | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_active_panel_update: Optional[EventType[()] | EventType[str]] = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_config_update: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_disconnect: Optional[EventType[()] | EventType[str]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_error: Optional[EventType[()] | EventType[str]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_global_filter_update: Optional[EventType[()] | EventType[list[Any]]] = None,
        on_layout_update: Optional[EventType[()] | EventType[list[Any]]] = None,
        on_load: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_select: Optional[EventType[()] | EventType[dict[str, Any]]] = None,
        on_toggle_settings: Optional[EventType[()] | EventType[bool]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "PerspectiveViewer":
        """Create a Perspective viewer.

        Args:
            *children: Not supported (the viewer renders its own UI).
            data: ------------------------------------------------------------ data source Inline data: a list of row dicts, a dict of column lists, or CSV text. Changing it calls ``table.replace()`` (the view config is preserved).
            schema: Column types ("string", "integer", "float", "boolean", "date", "datetime"). With ``data`` the table is created from the schema first, so types are enforced instead of inferred.
            index: Primary-key column. Updates with an existing key replace the row.
            limit: Rolling window: keep at most this many rows (mutually exclusive with index).
            table_name: Name of the table (defaults to the component id). Saved configs refer to tables by name, so set it when persisting layouts.
            url: Fetch the data from a URL (CSV, JSON, NDJSON or Apache Arrow).
            url_format: Force the URL format instead of inferring it from the extension.
            server_url: WebSocket of a perspective-python server. A path such as "/perspective" is resolved against the Reflex backend URL.
            server_table: Name of the hosted table to open (defaults to the first hosted table).
            server_mode: "server": virtual table, queries run in Python (default). "replicated": browser keeps a synced copy and computes views locally.
            update_rows: Streaming: every time this prop changes the rows are applied with ``table.update()`` (upsert when ``index`` is set, append otherwise).
            remove_keys: Streaming: every time this prop changes these primary keys are removed.
            config: ------------------------------------------------------ declarative state Full ``ViewerConfigUpdate`` applied with ``restore()``. The shortcut props below are merged on top of it.
            workspace: Multi-panel workspace (``WorkspaceConfigUpdate``) applied with ``restoreWorkspace()``: ``{"panels": {...}, "layout": {...}, ...}``.
            plugin: no description
            columns: no description
            group_by: no description
            split_by: no description
            filter: e.g. [["Sales", ">", 100], ["Region", "in", ["East", "West"]]]
            filter_op: no description
            sort: e.g. [["Profit", "desc"]]
            expressions: {"Margin": '"Profit" / "Sales"'}
            aggregates: {"Sales": "avg"}
            group_by_depth: no description
            group_rollup_mode: no description
            split_rollup_mode: no description
            plugin_config: no description
            columns_config: no description
            theme: no description
            title: no description
            settings: Whether the settings sidebar is open.
            edit_mode: Datagrid interaction mode ("EDIT" makes cells editable).
            auto_size: ---------------------------------------------------------- render policy
            auto_pause: no description
            throttle: Minimum milliseconds between renders while streaming.
            plugin_limits: {"Treemap": {"max_cells": 1_000_000, "max_columns": 1000}}
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: A datapoint/cell was clicked: {"row", "column_names", "config", "panel"}.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_load: ----------------------------------------------------------------- events Table loaded: {"table", "schema", "num_rows", "source"}.
            on_config_update: The user changed the view; receives the full saved config.
            on_select: Selection changed: {"selected", "row", "column_names", "insert_filters", "remove_filters", "panel"}.
            on_global_filter_update: Global (cross-panel) filters changed in a multi-panel viewer.
            on_layout_update: Panels were added/removed in a multi-panel viewer.
            on_active_panel_update: no description
            on_toggle_settings: no description
            on_disconnect: The WebSocket connection to the server was lost (auto-reconnects).
            on_error: no description
            **props: Component props, see the class attributes.

        Returns:
            The component.
        """
        ...

perspective_viewer = PerspectiveViewer.create

def save(viewer_id: str | Var[str], callback: Any) -> rx.event.EventSpec: ...
def restore(viewer_id: str | Var[str], config: dict | Var) -> rx.event.EventSpec: ...
def save_workspace(viewer_id: str | Var[str], callback: Any) -> rx.event.EventSpec: ...
def restore_workspace(
    viewer_id: str | Var[str], workspace: dict | Var
) -> rx.event.EventSpec: ...
def reset(viewer_id: str | Var[str], all: bool = False) -> rx.event.EventSpec: ...
def toggle_config(
    viewer_id: str | Var[str], force: bool | None = None
) -> rx.event.EventSpec: ...
def download(viewer_id: str | Var[str], method: str = "csv") -> rx.event.EventSpec: ...
def copy(viewer_id: str | Var[str], method: str = "csv") -> rx.event.EventSpec: ...
def export(
    viewer_id: str | Var[str], callback: Any, method: str = "csv"
) -> rx.event.EventSpec: ...
def update(
    viewer_id: str | Var[str], rows: list | dict | Var
) -> rx.event.EventSpec: ...
def remove(viewer_id: str | Var[str], keys: list | Var) -> rx.event.EventSpec: ...
def replace(
    viewer_id: str | Var[str], data: list | dict | str | Var
) -> rx.event.EventSpec: ...
def clear(viewer_id: str | Var[str]) -> rx.event.EventSpec: ...
def table_size(viewer_id: str | Var[str], callback: Any) -> rx.event.EventSpec: ...
def table_schema(viewer_id: str | Var[str], callback: Any) -> rx.event.EventSpec: ...
def add_panel(viewer_id: str | Var[str], config: dict | Var) -> rx.event.EventSpec: ...
def resize(viewer_id: str | Var[str]) -> rx.event.EventSpec: ...
